# Generated by Django 3.2.12 on 2023-02-24 11:01

import apps.common.db.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Task display')),
                ('tasks', apps.common.db.fields.JsonListTextField(verbose_name='Tasks')),
                ('options', apps.common.db.fields.JsonDictCharField(default='', max_length=1024, verbose_name='Options')),
                ('celery_task_id', models.UUIDField(default=None, null=True)),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('timedelta', models.FloatField(default=0.0, null=True, verbose_name='Time')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('is_success', models.BooleanField(default=False, verbose_name='Is success')),
                ('result', apps.common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='Adhoc raw result')),
                ('summary', apps.common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='Adhoc result summary')),
                ('host_data', apps.common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='hostdata')),
            ],
            options={
                'verbose_name': 'AdHoc execution',
                'db_table': 'qupot_ops_adhoc',
                'get_latest_by': 'date_start',
            },
        ),
        migrations.CreateModel(
            name='PlayBookModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('playbook_name', models.CharField(blank=True, default='', max_length=128, verbose_name='playbook_name')),
                ('options', apps.common.db.fields.JsonDictCharField(default='', max_length=1024, verbose_name='Options')),
                ('celery_task_id', models.UUIDField(default=None, null=True)),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('timedelta', models.FloatField(default=0.0, null=True, verbose_name='Time')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('is_success', models.BooleanField(default=False, verbose_name='Is success')),
                ('result', apps.common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='Playbook raw result')),
                ('summary', apps.common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='Playbook result summary')),
                ('hosts_data', apps.common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='hostdata')),
            ],
            options={
                'verbose_name': 'playbook execution',
                'db_table': 'qupot_ops_playbook',
                'get_latest_by': 'date_start',
            },
        ),
    ]
