- block:
    - name: install python dependent
      apt:
        name: "{{ item }}"
        state: "present"
      with_items:
        - bzip2
        - build-essential
        - libssl-dev
        - libffi-dev
        - python-dev-is-python3
        - zlib1g-dev

    - name: download python package
      get_url:
        validate_certs: no
        url: "{{ python_download_url }}"
        dest: "{{ base_dir }}/"
        timeout: "{{ download_timeout_online }}"

    - name: Extract python into
      unarchive:
        src: "{{ base_dir }}/{{ python_package }}"
        dest: "{{ base_dir }}"
        remote_src: yes

    - name: Configure python
      shell: ./configure
      args:
        chdir: "{{ base_dir }}/Python-{{ python_version }}"

    - name: make and install python
      shell: make && make install
      args:
        chdir: "{{ base_dir }}/Python-{{ python_version }}"
