version: "2.2"
services:

  nexus:
    restart: always
    image: registry.queco.cn/qudoor/sonatype/nexus3:3.43.0-${RT_ARCH}
    container_name: runtime-nexus
    ports:
      - ${RT_REPO_PORT}:8081
      - ${RT_REGISTRY_PORT}:8082
      - ${RT_REGISTRY_HOSTED_PORT}:8083
      - ${RT_REGISTRY_CHART_PORT}:8084
    volumes:
      - ./data/nexus-data/:/nexus-data
    healthcheck:
      test: ["CMD","curl","localhost:8081"]
      interval: 10s
      timeout: 10s
      retries: 20

  runtime:
    restart: always
    image: registry.queco.cn/qudoor/runtime:ansible-2.10.6-${RT_ARCH}
    container_name: runtime
    volumes:
      - ${RT_SECRET_PATH}:/root/.ssh
      - ./data/playbook:${CONTAINER_PLAYBOOK_PATH}
      - ./conf/:/etc/runtime/conf
    environment:
      - ANSIBLE_CONFIG=/etc/runtime/conf/ansible.cfg