- name: run qutrunk install packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - python3-pip
#
#- name: run pip install qutrunk packages
#  pip:
#    name: "{{ item }}"
#    extra_args: -i {{ registry_protocol }}://{{ dns_repository_hostname }}:{{ repo_port }}/repository/qudoor-pypi/simple/ --trusted-host {{ dns_repository_hostname }}
#    executable: pip3
#    virtualenv_python: python3
#  when: processing_unit == 'CPU'
#  with_items:
#    - qutrunk
#
#- name: run pip install qutrunk GPU packages
#  pip:
#    name: "{{ item }}"
#    extra_args: -i {{ registry_protocol }}://{{ dns_repository_hostname }}:{{ repo_port }}/repository/qudoor-pypi/simple/ --trusted-host {{ dns_repository_hostname }}
#    executable: pip3
#    virtualenv_python: python3
#  when: processing_unit == 'GPU'
#  with_items:
#    - 'qutrunk[gpu]'
#    - 'numpy==1.21.6' # 版本对不上 无法运行 from numba import cuda 但不会报错
