# Generated by Django 3.2.12 on 2023-03-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='taskspecmodel',
            name='dependents',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='taskspecmodel',
            name='processing_unit',
            field=models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU')], default='CPU', max_length=32),
        ),
        migrations.AddField(
            model_name='taskspecmodel',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='runtime.taskmodel'),
        ),
        migrations.AddField(
            model_name='taskstatusmodel',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='runtime.taskmodel'),
        ),
        migrations.AlterField(
            model_name='credentialmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hostmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='komodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ntpservermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='runtimeappmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tasknodemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskregistrymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskspecmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskstatusconditionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskstatusconditionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='taskstatusmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskstatusmodel',
            name='status',
            field=models.CharField(default='Initializing', max_length=255),
        ),
    ]
