#!/bin/bash

action=$1
target=$2
QU_BASE=/opt

set -e

if [[ -f ${QU_BASE}/qupot/scripts/const.sh ]];then
  source ${QU_BASE}/qupot/scripts/const.sh
elif [ -f $(pwd)/qupot/scripts/const.sh ]; then
  source $(pwd)/qupot/scripts/const.sh
fi

function usage() {
   echo "QuPot 控制脚本"
   echo
   echo "Usage: "
   echo "  ./quctl [COMMAND] [ARGS...]"
   echo "  ./quctl --help"
   echo "Commands: "
   echo "  status    查看 QuPot 服务运行状态"
   echo "  start     启动 QuPot 服务"
   echo "  stop      停止 QuPot 服务"
   echo "  restart   重启 QuPot 服务"
   echo "  reload    重新加载 QuPot 服务"
   echo "  uninstall 卸载 QuPot 服务"
   echo "  pull      在线拉取 QuPot 最新镜像"
   echo "  logs      查看 QuPot 日志信息"
   echo "  version   查看 QuPot 版本信息"
}

function status() {
   echo
   cd ${QU_BASE}/qupot; docker-compose ps
}
function start() {
   colorMsg $green "[Starting QuPot]"
   cd ${QU_BASE}/qupot; docker-compose up -d  ${target}
}
function stop() {
   colorMsg $green "[Stopping QuPot]"
   cd ${QU_BASE}/qupot; docker-compose down ${target}
}
function restart() {
   stop
   start
}
function reload() {
   echo
   cd ${QU_BASE}/qupot; docker-compose up -d ${target}
}
function logs() {
   echo
   cd ${QU_BASE}/qupot; docker-compose logs ${target}
}
function pull() {
   echo
   cd ${QU_BASE}/qupot; docker-compose pull ${target}
}
function version() {
   echo  "$CURRENT_QU_VERSION"
}

function main() {
    case "${action}" in
      status)
         status
         ;;
      start)
         start
         ;;
      stop)
         stop
         ;;
      restart)
         restart
         ;;
      reload)
         reload
         ;;
      uninstall)
         bash "${QU_BASE}/qupot/scripts/uninstall.sh" ${target}
         ;;
      version)
         version
         ;;
      pull)
         pull
         ;;
      logs)
         logs
         ;;
      help)
         usage
         ;;
      --help)
         usage
         ;;
      *)
         echo "不支持的参数，请使用 help 或 --help 参数获取帮助"
         ;;
    esac
}
main
