# Generated by Django 3.2.12 on 2023-03-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirecord',
            name='action',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
